_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.12
            "5": 0.19.11
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": linux-x86_64
1st_layer_inputs:
    value: 128
base_topology:
    value: VGG7_float_v1
batch_size:
    value: 1024
dropout_conv:
    value: 0
dropout_dense:
    value: 0
epochs:
    value: 100
filters_conv:
    value: 4
filters_dense:
    value: 64
lr:
    value: 0.001
lr_scheduler:
    value: EXP
lr_scheduler_halflife:
    value: 10
lr_scheduler_t0:
    value: 5
lr_scheduler_tmult:
    value: 1
num_classes:
    value: 2
train_snr_cutoff:
    value: 30
