_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 1024
epochs:
    value: 1
lr:
    value: 0.001
lr_scheduler:
    value: EXP
lr_scheduler_halflife:
    value: 10
lr_scheduler_t0:
    value: 5
lr_scheduler_tmult:
    value: 1
train_snr_cutoff:
    value: 30
